apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  #
  - level: None
    userGroups: ["system:serviceaccounts", "system:serviceaccounts:kube-system", "system:serviceaccounts:monitoring", "system:authenticated"]
  #
  - level: None
    users: ["system:apiserver"]
    userGroups: ["system:masters"]
    verbs: ["get", "watch", "configmaps"]
    resources:
      - group: ""
        resources: ["endpointslices", "configmaps", "namespaces", "secrets"]
  #
  - level: None
    users: ["system:kube-controller-manager"]
    userGroups: ["system:authenticated"]
    verbs: ["update"]
    resources: 
      - group: "coordination.k8s.io"
        resources: ["leases"]
  #
  - level: None
    # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
    users: ["system:unsecured"]
    namespaces: ["kube-system"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["configmaps"]
  #
  - level: None
    users: ["kubelet"] # legacy kubelet identity
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  #
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get", "patch", "watch"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  #
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["secrets"]
  #
  - level: None
    users:
      - system:kube-controller-manager
      - system:kube-scheduler
      - system:serviceaccount:kube-system:endpoint-controller
    verbs: ["get", "update", "watch"]
    namespaces: ["kube-system"]
    resources:
      - group: "" # core
        resources: ["endpoints", "leases"]
  # 
  - level: None
    nonResourceURLs:
      - /healthz*
      - /version
      - /livez*
      - /metrics
  # Don't log events requests.
  - level: None
    resources:
      - group: "events.k8s.io"
        resources: ["events"]
  #
  - level: None
    resources:
      - group: "apiregistration.k8s.io"
      - group: "coordination.k8s.io"
      - group: "admissionregistration.k8s.io"
  # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
  # so only log at the Metadata level.
  - level: Metadata
    resources:
      - group: ""  # core
        resources: ["secrets", "configmaps"]
      - group: authentication.k8s.io
        resources: ["tokenreviews"]
  # Log pvc/pv requests to capture volume details
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    verbs: ["create", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["pods", "replicacontrollers", "container"]
      - group: "apps"
        resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
      - group: "batch"
        resources: ["jobs", "cronjobs"]
      - group: "extensions" # necessary for pre-1.12 clusters
        resources: ["daemonsets", "deployments", "replicasets"]
  # 
  - level: RequestResponse
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: "networking.k8s.io" 
  # 
  - level: Metadata
    verbs: ["create", "update", "delete", "patch"]
