apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gorestapi-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ping
        pathType: Prefix 
        backend:
          service:
            name: gorestapi1 
            port:
              number: 8080
      - path: /newsfeed
        pathType: Prefix
        backend:
          service:
            name: gorestapi2
            port:
              number: 8080
status:
  loadBalancer: {}
