apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gorestapi 
  name: gorestapi 
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080 
    targetPort: 8080 
  selector:
    app: gorestapi 
#  type: ClusterIP 
status: {}
