---
# tasks file for general setup
- name: Install additional packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 20
  delay: 2
  vars:
    packages:
      - bash-completion
      - direnv

- name: Turn On Color Prompt
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "force_color_prompt=yes"
    regexp: '#?force_color_prompt=yes'
    state: present

- name: More User Friendly List Aliases
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
    state: present
  loop:
    - { alias: ll, command: "ls -lFh" }
    - { alias: la, command: "ls -lFhA" }
    - { alias: l,  command: "ls -CF" }

- name: Expand Bash History
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "{{ item.key }}={{ item.value }}"
    regexp: '^#?\s*{{ item.key }}='
    state: present
  loop:
    - { key: HISTCONTROL,  value: ignoreboth }
    - { key: HISTSIZE,     value: 100000 }
    - { key: HISTFILESIZE, value: 100000 }
    - { key: HISTIGNORE,   value: "'ls:bg:fg:history'" }

- name: Set Additional Shell Options
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "shopt -s {{ item }}"
    regexp: '^#?\s*shopt -s {{ item }}'
    state: present
  loop:
    - globstar

- name: Enable Direnv
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: 'eval "$(direnv hook bash)"'
    state: present
  when: ansible_distribution_release != 'trusty'

- name: Use Arrow Keys to Search History
  lineinfile:
    dest: /etc/inputrc
    line: "{{ item }}"
    state: present
  become: yes
  loop:
    - '"\e[B": history-search-forward'
    - '"\e[A": history-search-backward'

- name: Use Magic Space in Bash
  blockinfile:
    dest: /etc/inputrc
    block: |
      $if Bash
      Space: magic-space
      $endif
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK magic-space"
  become: yes
...
